### ISSUE TITLE
Typo in "Tuner Not Allocated" popup

### ISSUE THREAD

**Issue by RFComms** [RedhawkSDR/gov.redhawk.ide#13]
When allocating a tuner, the "Tuner Not Allocated" popup mentions "requestion" which is not a word.  Perhaps "request"? 

> Allocation failed.  Device returned 'false' to allocation requestion. 
![screenshot from 2019-01-15 11-22-47](https://user-images.githubusercontent.com/45981546/51254707-9f870100-196f-11e9-8235-16a0e4f88c3f.png)

**Comment by MichelleD123** [comment]
Thank you for finding the typographical error. This has been added to our backlog.
